# This file is a template, and might need editing before it works on your project.
image: python:latest

before_script:
  - python -V                                   # Print out python version for debugging
  - pip install time
  - pip install os
  - pip install threading

  - pip install requests
  
test:
  script:
  - python downloadXKCD.py test
  - python run_downloadXKCD.py test
  - pip install tox flake8  # you can also use tox
  - tox -e py36,flake8

run:
  script:
  - python downloadXKCD.py bdist_wheel
  - python run_downloadXKCD.py bdist_wheel
  # an alternative approach is to install and run:
  - pip install dist/*
  # run the command here
  artifacts:
    paths:
    - dist/*.whl

pages:
  script:
  - pip install sphinx sphinx-rtd-theme
  - cd doc ; make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master


